# Generated by Django 5.0.6 on 2024-05-08 09:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='')),
                ('model', models.CharField(max_length=100, verbose_name='')),
                ('launch_date', models.DateTimeField(default=datetime.datetime(2024, 5, 22, 12, 11, 39, 11204), verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('FAC', 'factory'), ('STO', 'store'), ('IND', 'individual entepreneur')], max_length=3)),
                ('name', models.CharField(max_length=100, verbose_name='Provide Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Provide Email')),
                ('country', models.CharField(max_length=100, verbose_name='Provider Country')),
                ('citi', models.CharField(max_length=100, verbose_name='Provider Citi')),
                ('street', models.CharField(max_length=100, verbose_name='Provider Street')),
                ('house_number', models.IntegerField(verbose_name='Provider House Number')),
                ('provider_debt', models.BigIntegerField(blank=True, null=True, verbose_name='')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 5, 8, 12, 11, 39, 11204), verbose_name='Creation time')),
                ('products', models.ManyToManyField(to='sales_network.product')),
                ('self_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales_network.provider')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
    ]
