# Generated by Django 5.0.6 on 2024-05-12 20:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='launch_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 23, 42, 32, 180508), verbose_name=''),
        ),
        migrations.AlterField(
            model_name='provider',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 12, 23, 42, 32, 196132), verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='level',
            field=models.IntegerField(choices=[('1', 'factory'), ('2', 'store'), ('3', 'individual entepreneur')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='provider',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='sales_network.product'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_debt',
            field=models.BigIntegerField(default=0, verbose_name=''),
        ),
    ]
