# Generated by Django 5.0.6 on 2024-05-12 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='launch_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 22, 19, 28, 589303), verbose_name=''),
        ),
        migrations.AlterField(
            model_name='provider',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 12, 22, 19, 28, 590322), verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_debt',
            field=models.BigIntegerField(default=0, verbose_name=''),
        ),
    ]
