# Generated by Django 5.0.6 on 2024-05-12 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0002_alter_product_launch_date_alter_provider_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='launch_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 22, 26, 36, 405044), verbose_name=''),
        ),
        migrations.AlterField(
            model_name='provider',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 12, 22, 26, 36, 405044), verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='sales_network.product'),
        ),
    ]
