# Generated by Django 5.0.6 on 2024-05-12 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_network', '0004_alter_product_launch_date_alter_provider_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='launch_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 23, 18, 27, 913111), verbose_name=''),
        ),
        migrations.AlterField(
            model_name='provider',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 12, 23, 18, 27, 913111), verbose_name='Creation time'),
        ),
    ]
